# Generated by Django 2.2.5 on 2019-10-16 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteReimu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_url', models.URLField(blank=True)),
                ('player_name', models.CharField(max_length=16)),
                ('creat_date', models.DateTimeField(default=datetime.datetime.now)),
                ('priority', models.IntegerField(default=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='mahjongrecord',
            name='is_finished',
        ),
    ]
