# Generated by Django 2.2.5 on 2019-10-17 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteReimu', '0002_auto_20191016_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_url', models.URLField(blank=True)),
                ('player_name', models.CharField(max_length=16)),
                ('creat_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='mahjongrecord',
            name='save_url',
            field=models.URLField(blank=True),
        ),
    ]
